/**
 * Định nghĩa ngôn ngữ
 * Cách 1: [từ khóa, tiếng việt, tiếng anh]
 */
App_Dictionary = [
  ['key', 'vi', 'en'],
  // ['vi', 'en'],

  //common_text
  ['c_home', 'Trang chủ', 'Home'],
  ['c_homeAdmin', 'Trang chủ quản trị', 'Home'],
  ['c_create', 'Thêm mới', 'Add New'],  
  ['c_list', 'Danh sách', 'List'],
  ['c_update', 'Cập nhật', 'Update'],
  ['c_delete', 'Xóa', 'Delete'],
  ['c_detail', 'Chi tiết', 'Detail'],
  ['c_view', 'Xem', 'view'],
  ['c_close', 'Đóng', 'Close'],
  ['c_search', 'Tìm kiếm', 'Search'],
  ['c_filter', 'Lọc dữ liệu', 'Filter'],
  ['c_back', 'Quay lại', 'Back'],
  ['c_success', 'thành công', ''],
  ['c_error', 'không thành công', ''],
  ['c_record', 'bản ghi', ''],
  ['c_fromDate', 'Từ ngày', ''],
  ['c_toDate', 'Đến ngày', ''],
  ['c_order', 'Xắp xếp', ''],
  ['c_drag', 'Kéo thả', ''],
  ['c_select', 'Chọn', ''],

  //common_alert 
  ['c_addSuccess', 'Thêm mới thành công', 'Add new success'],
  ['c_addError', 'Thêm mới không thành công', ''],
  ['c_updateSuccess', 'Cập nhật thành công', ''],
  ['c_updateError', 'Cập nhật không thành công', ''],
  ['c_deleteSuccess', 'Xóa thành công', ''],
  ['c_deleteError', 'Xóa không thành công', ''],
  ['c_deleteConfirm', 'Bạn có chắc chắn xóa bản ghi này không?', ''],
  ['c_notAllowAccess', 'Không có quyền truy cập trang này', ''],
  ['c_emptyRecord', 'Bạn chưa chọn bản ghi nào', ''],
  ['c_loginAgain', 'Bạn cần đăng nhập trước', ''],

  //validation
  ['valid', 'Được phép', ''],
  ['valid_required', 'Vui lòng nhập giá trị', ''],
  ['valid_email', 'Email không đúng định dạng', ''],
  ['valid_phone', 'Số điện thoại không đúng định dạng', ''],
  ['valid_link', 'Liên kết không đúng định dạng', ''],
  ['valid_imageLink', 'Liên kết ảnh không đúng định dạng', ''],
  ['valid_sign', 'Không được nhập ký tự có dấu', ''],
  ['valid_space', 'Không được nhập ký tự trắng', ''],
  ['valid_script', 'Không được nhập ký tự đặc biệt', ''],
  ['valid_az09', 'Chỉ được nhập từ a đến z, từ 0 đến 9', ''], 
  ['valid_textFirst', 'Ký tự đầu tiên phải là chữ', ''],
  ['valid_dateTime', 'Ngày giờ không đúng định dạng', ''],
  ['valid_date', 'Ngày không đúng định dạng', ''],
  ['valid_year', 'Năm không đúng định dạng', ''],
  ['valid_month', 'Tháng không đúng định dạng', ''],
  ['valid_int', 'Phải là số nguyên', ''],
  ['valid_float', 'Phải là số nguyên hoặc số thập phân', ''],
  ['valid_tuNgay', 'Từ ngày phải nhỏ hơn hoặc bằng đến ngày', ''],
  ['valid_denNgay', 'Đến ngày phải lớn hơn hoặc bằng từ ngày', ''],
  ['valid_upload', 'Vui lòng chọn file', ''],
  ['valid_file', 'file', ''],
  ['valid_character', 'ký tự', ''],
  ['valid_max', 'Không được lớn hơn', ''],
  ['valid_min', 'Không được nhỏ hơn', ''],
  ['valid_length', 'Giá trị nhập phải là', ''],
  ['valid_requiredUpload', 'Vui lòng chọn', ''],

  //login
  ['login', 'Đăng nhập', ''],
  ['login_loginFalse', 'Tài khoản hoặc mật khẩu không đúng', ''],
  ['login_account', 'Tên đăng nhập', ''],
  ['login_password', 'Mật khẩu', ''],
  ['login_remember', 'Ghi nhớ đăng nhập', ''],  

  //logout
  ['logout', 'Đăng xuất', ''],
  ['logout_all', 'Có đăng xuất khỏi các thiết bị khác?', ''],
  ['logout_logoutFalse', 'Đăng xuất không thành công', ''],

  //datatable default
  ['datatable_sum', 'Tổng số', ''],
  ['datatable_record', 'bản ghi', ''],
  ['datatable_emptyValue', 'Không có dữ liệu hiển thị', ''],
  ['datatable_loading', 'Đang tải dữ liệu', ''],
  ['datatable_first', 'Đầu', ''],
  ['datatable_last', 'Cuối', ''],
  ['datatable_next', 'Trang trước', ''],
  ['datatable_prev', 'Trang sau', ''],
  ['datatable_action', 'Thao tác', ''],
  ['datatable_exportExcel', 'Xuất excel', ''],
  ['datatable_stt', 'STT', ''],
  ['datatable_alertOrder', 'Trạng thái sắp xếp phải ở chế độ tăng dần', ''],

  //select2
  ['select2_emptyValue', 'Không có kết quả', ''],
  ['select2_searching','Tìm kiếm',''],
  
  ['order', 'đơn hàng', ''],
  ['Order', 'Đơn hàng', ''],
  ['order_firstname', 'Tên đệm', ''],
  ['order_lastname', 'Tên', ''],
  ['order_phoneNumber', 'Số điện thoại', ''],
  ['order_email', 'Email', ''],
  ['order_country', 'Đất nước', ''],
  ['order_city', 'Thành phố', ''],
  ['order_state', 'Bang', ''],
  ['order_line1', 'Dòng 1', ''],
  ['order_line2', 'Dòng 2', ''],  
  ['order_postcode', 'Mã code', ''],
  ['order_productName', 'Tên sản phẩm', ''],
  ['order_quantity', 'Số lượng', ''],
  ['order_price', 'Giá', ''],
  ['order_shippingPrice', 'Phí ship', ''],
  ['order_discountPrice', 'Giảm giá', ''],
  ['order_createdTime', 'Ngày tạo', ''],
  
  ['faq', 'câu hỏi thường gặp', ''],
  ['Faq', 'Câu hỏi thường gặp', ''],
  ['faq_question', 'Câu hỏi', ''],
  ['faq_answer', 'Câu trả lời', ''],
  ['faq_index', 'Thứ tự', ''],
  ['faq_visible', 'Hiện', ''],

  ['account', 'tài khoản', ''],
  ['Account', 'Tài khoản', ''],
  ['account_firstName', 'First name', ''],
  ['account_lastName', 'Last name', ''],
  ['account_phoneNumber', 'Số điện thoại', ''],
  ['account_linkedAccounts', 'Tài khoản Linked', ''],
  ['account_devices', 'Thiết bị', ''],

  ['feedback', 'phản hồi', ''],
  ['Feedback', 'Phản hồi', ''],
  ['feedback_name', 'Tên', ''],
  ['feedback_email', 'Email', ''],
  ['feedback_phone', 'Số điện thoại', ''],
  ['feedback_idRead', 'Đã xem', ''],
  ['feedback_status', 'Trạng thái', ''],
  ['feedback_message', 'Nội dung', ''],
  ['feedback_new', 'Mới', ''],
  ['feedback_processing', 'Đang xử lý', ''],
  ['feedback_deleted', 'Đã xóa', ''],
  ['feedback_closed', 'Đã đóng', ''],
  ['feedback_createdTime', 'Ngày tạo', ''],

  ['', '', ''],
];